const {chromium}=require('playwright');
const AxeBuilder=require('@axe-core/playwright').default;
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||(require('node:fs').existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.setDefaultTimeout(20000);page.setDefaultNavigationTimeout(30000);const base=process.env.ORDERPROOF_URL||'http://127.0.0.1:8080';const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function axe(label){console.log("Checking "+label);const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[],label)}
await page.goto(base+'/app');await page.getByRole('link',{name:'How it works',exact:true}).click();await page.waitForURL(base+'/#how');await page.locator('#how').waitFor();await page.waitForFunction(()=>window.scrollY>0&&document.getElementById('how').getBoundingClientRect().top>=0&&document.getElementById('how').getBoundingClientRect().top<window.innerHeight/2);
await page.goto(base+'/review');await page.getByRole('heading',{name:'One question. One handoff. One complete record.'}).waitFor();await axe('reviewer guide');
await page.goto(base);await page.getByRole('heading',{name:'Helpful answers. Human connection. Nothing lost.'}).waitFor();await axe('landing');await page.screenshot({path:'/tmp/orderproof-landing.png',fullPage:true});
await page.getByRole('button',{name:'Explore the demo'}).click();await page.getByRole('heading',{name:'A little more clarity. A lot better support.'}).waitFor();await axe('overview');await page.screenshot({path:'/tmp/orderproof-workspace.png',fullPage:true});
await page.locator('.sideitem[data-action="inbox"]').click();await page.getByRole('note').filter({hasText:'no Bedrock calls'}).waitFor();await axe('inbox');await page.screenshot({path:'/tmp/orderproof-inbox.png',fullPage:true});
await page.getByRole('button',{name:'Join conversation'}).click();await page.getByLabel('Reply as Alex').fill('I can help with your return.');await page.getByRole('button',{name:'Send reply'}).click();await page.locator('.msgbody').filter({hasText:'I can help with your return.'}).waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Close conversation',exact:true}).click();await page.getByText('This conversation is read-only.',{exact:true}).waitFor();for(const target of ['knowledge','plans','settings','records']){await page.locator('.sideitem[data-action="'+target+'"]').click();await axe(target)}await page.locator('.sideitem[data-action="install"]').click();await axe('install');await page.screenshot({path:'/tmp/orderproof-install.png',fullPage:true});
await page.goto(base+'/widget-demo');await page.getByLabel('Your name').fill('Maya');await page.locator('input[type=checkbox]').check();await page.getByRole('button',{name:'Start conversation'}).click();await page.getByRole('textbox',{name:'Your message'}).fill('How do returns work?');await page.getByRole('button',{name:'Send message'}).click();await page.getByText('Demo response:',{exact:false}).waitFor();await page.getByRole('button',{name:'Talk to a person'}).click();await page.getByText('Your request is in the queue.',{exact:false}).waitFor();await page.getByText('Unsaved fictional demo',{exact:false}).waitFor();await axe('widget');await page.screenshot({path:'/tmp/orderproof-widget.png',fullPage:true});
await page.goto(base+'/integration-demo');const ready=page.waitForEvent('framenavigated',{predicate:f=>f.url().includes('/widget-demo'),timeout:20000});await page.evaluate(()=>window.OrderProof.open());const frame=await ready;await frame.getByLabel('Your name').waitFor();assert.equal(await page.locator('iframe').count(),0); // closed shadow root intentionally isolates merchant CSS
await page.screenshot({path:'/tmp/orderproof-embed.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.goto(base);await page.getByRole('button',{name:'Explore the demo'}).click();await axe('mobile overview');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile horizontal overflow');await page.screenshot({path:'/tmp/orderproof-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);await browser.close();console.log('Support browser flows and accessibility checks passed.');})().catch(e=>{console.error(e);process.exit(1)});
